config/routes.rb
TrackYourTrailer::Application.routes.draw do
  devise_for :users
  resources :movies
  get '/all_movies' => 'movies#all_movies'

  resources :users do
    resources :movies, :controller => 'users/movies', only:[:create, :update, :new, :destroy]
  end

  get '/login' => 'sessions#new', :as => 'login'
  get '/logout' => 'sessions#destroy', :as => 'logout'
  post '/sessions' => 'sessions#create'

  get '/results' => 'search#index', :as => 'results'
  get '/search' => 'search#new', :as => 'search'

  get '/v/:text_token' => 'users#verify_text'

  root 'movies#index'

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :user_movies
  has_many :users, :through => :user_movies

  validates :name, :rotten_tomatoes_uri, :presence => true
  validates :rotten_tomatoes_uri, :uniqueness => true

  def self.create_from_rotten(movie_hash)
    original_movie_poster = defend_against_thumbnail_images(movie_hash["posters"]["original"])

    Movie.where(:rotten_tomatoes_uri => movie_hash["id"]).first_or_create(
        :name => movie_hash["title"],
        :release_date_theater => movie_hash["release_dates"]["theater"],
        :release_date_dvd => movie_hash["release_dates"]["dvd"],
        :poster_image => original_movie_poster,
        :rotten_tomatoes_uri => movie_hash["id"],
        :poster_image_small => movie_hash["posters"]["thumbnail"],
        :synopsis => movie_hash["synopsis"],
        :rotten_tomatoes_link => movie_hash["links"]["alternate"]
      )
  end

  def update_from_rotten(movie_hash)
    original_movie_poster = Movie.defend_against_thumbnail_images(movie_hash["posters"]["original"])

    self.update(
        :name => movie_hash["title"],
        :release_date_theater => movie_hash["release_dates"]["theater"],
        :release_date_dvd => movie_hash["release_dates"]["dvd"],
        :poster_image => original_movie_poster,
        :rotten_tomatoes_uri => movie_hash["id"],
        :poster_image_small => movie_hash["posters"]["thumbnail"],
        :synopsis => movie_hash["synopsis"],
        :rotten_tomatoes_link => movie_hash["links"]["alternate"]
    )
  end

  private

  def self.movies_released(days_until = 0)
    theater = Movie.theater_movies_released(days_until)
    dvd = Movie.dvd_movies_released(days_until)
    theater.concat(dvd)
  end

  def self.theater_movies_released(days_until = 0)
    Movie.where(:release_date_theater => Time.zone.now.days_since(days_until).beginning_of_day)
  end

  def self.dvd_movies_released(days_until = 0)
    Movie.where(:release_date_dvd => Time.zone.now.days_since(days_until).beginning_of_day)
  end

  def self.find_movies_without_release_dates
    self.where("release_date_dvd is null OR release_date_theater is null")
  end

  def self.defend_against_thumbnail_images(poster_url)
    if poster_url.include?('tmb')
      poster_url.gsub('tmb', 'ori')
    elsif poster_url.include?('_thumb')
      poster_url.gsub('_thumb', '')
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable, :confirmable
  has_many :user_movies
  has_many :movies, :through => :user_movies

  phony_normalize :phone_number, :default_country_code => "US"

  validates_uniqueness_of :email

  after_save :verify_phone_number

  def self.users_for(notify_day = 0)
     User.joins(:movies).where(:movies => {:id => Movie.movies_released(notify_day)}).uniq
  end

  def movie_notifications(notify_day = 0)
    theater = self.movies.where(:release_date_theater => Time.zone.now.days_since(notify_day).beginning_of_day)
    dvd = self.movies.where(:release_date_dvd => Time.zone.now.days_since(notify_day).beginning_of_day)
    theater.concat(dvd)
  end

  def text_notification(notify_day)
    self.movie_notifications(notify_day).collect(&:name).to_sentence[0..140]
  end

  def send_text_verification
    self.update_column(:text_token, Random.rand(8999) + 1000)
    begin
      TwilioApi.send_verification(self)
    rescue
    end
  end

  def verify_phone_number
    if self.phone_number_changed?
      self.update_column(:phone_verified, false)
      self.send_text_verification
    end
  end

end

app/models/user_movie.rb
class UserMovie < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception
  before_filter :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :phone_number, :email, :current_password, :password) }
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :phone_number, :email, :password) }
  end

  def after_sign_in_path_for(resource)
    root_path
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  skip_before_filter :authenticate_user!, :only => [:index, :all_movies, :show]
  DEFAULT_POSTER_IMAGES = ["http://images.rottentomatoescdn.com/images/redesign/poster_default.gif",
                           "http://d1rjibvava1hwe.cloudfront.net/static/images/redesign/poster_default.gif",
                           "http://d1rjibvava1hwe.cloudfront.net/static/images/redesign/poster_default_thumb.gif",
                           "http://d3biamo577v4eu.cloudfront.net/static/images/redesign/poster_default.gif",
                           "http://d3biamo577v4eu.cloudfront.net/static/images/redesign/poster_default_thumb.gif"]

  def index
    @movies = Movie.where.not(poster_image: DEFAULT_POSTER_IMAGES ).where("release_date_theater is not null").order(release_date_theater: :desc).limit(9).reverse
  end

  def all_movies
    @movies = Movie.all.where.not(poster_image: DEFAULT_POSTER_IMAGES).where("release_date_theater > ? or release_date_dvd > ?", Time.now, Time.now)
  end

  def show
    @movie = Movie.find(params[:id])
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def index
    @results = RottenTomatoesApi.seed_search(params[:q])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  skip_before_action :login_required, :only => [:new, :create]

  def new
  end

  def create
    user = User.find_by(:email => params[:email])
    if user && user.authenticate(params[:password])
      login(user.id)
      redirect_to(root_path)
    else
      render :new
    end
  end

  def destroy
    reset_session
    redirect_to(root_path)
  end

end

app/controllers/users/movies_controller.rb
class Users::MoviesController < ApplicationController

  def create
    if params[:user_id].to_i == current_user.id
      UserMovie.find_or_create_by(:user_id => params[:user_id], :movie_id => params[:movie_id])
      redirect_to user_path(params[:user_id])
    else
      redirect_to :back, :notice => "You can't add a movie to another user!"
    end
  end

  def destroy
    @user_movie = UserMovie.where(:user_id => params[:user_id], :movie_id => params[:id])
    UserMovie.destroy(@user_movie)

    redirect_to :back
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :authenticate_user!, :only => [:verify_text]

  def index
    @users = User.all
    redirect_to root_path
  end

  def show
    if params[:id].to_i == current_user.id
      @user = User.find(params[:id])
    else
      redirect_to root_path, :notice => "You aren't that user!"
    end
  end

  def verify_text
    user = User.find_by(:text_token => params[:text_token])
    user.update(
      :text_token => nil,
      :phone_verified => true
    )
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users/movies_helper.rb
module Users::MoviesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>TrackYourTrailer</title>
          <link href="http://fonts.googleapis.com/css?family=Arvo" rel="stylesheet" type="text/css">
          <%= stylesheet_link_tag "application", media: "all" %>
          <%= javascript_include_tag "application" %>
          <%= csrf_meta_tags %>
          <%= favicon_link_tag 'favicon.png' %>
    </head>
    <body class="home">
        <%= render "shared/header" %><!-- Begin Header & Container-->

            <!-- <#% if current_user %> -->
                <%= render "shared/main_nav" %>
                <%= render "shared/mobile_nav" %>
                <%= render "shared/search" %>
            <!-- <#% end %> -->


        <p class="notice"><%= raw(notice) %></p>
        <p class="alert"><%= alert %></p>

            <%= yield %>

        </div> <!-- End Container -->
    </div><!-- End Header -->

        <%= render "shared/footer" %>

    <!-- Scroll to Top -->
    <div id="toTop" class="hidden-phone hidden-tablet">Back to Top</div>

    </body>
</html>

app/views/movies/all_movies.html.erb
 <div class="row">

        <!-- Gallery Items
        ================================================== -->
        <div class="span12 gallery">

            <div class="row clearfix">
                <ul class="gallery-post-grid holder">

                    <!-- Gallery Item 1 -->
                <% @movies.each do |movie| %>
                    <li  class="span4 gallery-item" data-id="id-1" data-type="tag1">
                     <span class="link-like" onclick="window.location='<%= movie_path(movie) %>'">
                        <span class="gallery-hover-3col hidden-phone hidden-tablet">
                            <span class="gallery-icons">
                                <% if current_user %>
                                    <%= link_to "", user_movies_path(current_user, :movie_id => movie), :method => :post, class: "item-details-link" %>
                                <% else %>
                                    <%= link_to "", new_user_registration_path, class: "item-details-link" %>
                                <% end %>
                            </span>
                        </span>
                    </span>
                        <a href="<%= movie_path(movie) %>"><img src="<%= movie.poster_image %>" class="thumbnail-movie" alt="Gallery"></a>
                        <span class="project-details"><a href="<%= movie_path(movie) %>"><%= movie.name %></a><br>Theaters: <%= movie.release_date_theater ? movie.release_date_theater.to_formatted_s(:nice_date) : "Check back soon!" %><br>DVD: <%= movie.release_date_dvd ? movie.release_date_dvd.to_formatted_s(:nice_date) : "Check back soon!" %></span>
                    </li>
                <% end %>

                </ul>
            </div>


        </div><!-- End gallery list-->

    </div><!-- End container row -->

app/views/movies/index.html.erb
<div class="container">

    <div class="row headline"><!-- Begin Headline -->



        <!-- Slider Carousel
        ================================================== -->
        <div class="span12 gallery">
            <div class="flexslider">
              <ul class="slides">
                <% @movies.each do |movie| %>
                <li><a href="<%= movie_path(movie) %>"><img src="<%= movie.poster_image %>" class="thumbnail-movie"></a></li>
                <% end %>
              </ul>
            </div>
        </div>


        <div class="span12 gallery">
            <br>
            <br>
            <h5 class="title-bg">About &nbsp
                <small> Track Your Trailer</small>
                <button class="btn btn-mini hidden-phone" type="button">View Portfolio</button>
            </h5>
        </div>

        <!-- Headline Text
        ================================================== -->
        <div class="span12 gallery">
            <!-- <h3>Track Your Trailer</h3> -->
            <!--<p class="subheadline" align="center">-Find a movie you like.<br>-<em>Track</em> it.<br>-We'll let you know when it's out!</p>-->
            <p>
                <div class="subheadline" style="text-align: center;">

                          <p><br>Welcome to Track Your Trailer!<br><br>
                            Search for upcoming movies you want to see.<br>
                            Add them to your personal list.<br>
                            We’ll send you text and email reminders when they come out.<br>
                            Never worry about missing great movies again.<br><br>
                            We've got your back.<br><br></p>

                          <% if !current_user %>
                            <%= link_to "Sign Up Now >>", new_user_registration_path %><br><br>
                            <% end %>
                </div>
            </p>
        </div>
    </div>

    <div class="row gallery-row"><!-- Begin Gallery Row -->

        <div class="span12 gallery">
            <h5 class="title-bg">Upcoming Movies &nbsp
                <small>For You</small>
                <button class="btn btn-mini hidden-phone" type="button">View Portfolio</button>
            </h5>
            <div class="row clearfix">
                <ul class="gallery-post-grid holder">

                    <!-- Gallery Item 1 -->
                <% @movies.each do |movie| %>
                    <li  class="span4 gallery-item" data-id="id-1" data-type="tag1">
                        <span class="link-like" onclick="window.location='<%= movie_path(movie) %>'">
                            <span class="gallery-hover-3col hidden-phone hidden-tablet">
                                <span class="gallery-icons">
                                    <% if current_user %>
                                        <%= link_to "", user_movies_path(current_user, :movie_id => movie), :method => :post, class: "item-details-link" %>
                                    <% else %>
                                        <%= link_to "", new_user_registration_path, class: "item-details-link" %>
                                    <% end %>
                                </span>
                            </span>
                        </span>

                        <a href="<%= movie_path(movie) %>"><img src="<%= movie.poster_image %>" class="thumbnail-movie" alt="Gallery"></a>
                        <span class="project-details"><a href="<%= movie_path(movie) %>"><%= movie.name %></a><br>Theaters: <%= movie.release_date_theater ? movie.release_date_theater.to_formatted_s(:nice_date) : "Check back soon!" %><br>DVD: <%= movie.release_date_dvd ? movie.release_date_dvd.to_formatted_s(:nice_date) : "Check back soon!" %></span>
                    </li>
                <% end %>

                </ul>
            </div>

    </div><!-- End Gallery Row -->








</div>
</div>
</div>

</div> <!-- End Container -->

app/views/movies/show.html.erb
<!-- TODO - update the user id in this path -->





<!-- Page Content
    ================================================== -->
    <div class="row">

        <!-- Gallery Items
        ================================================== -->
        <div class="span12 gallery-single">

            <div class="row">
                <div class="span6">
                    <img src=<%= @movie.poster_image %> class="thumbnail-movie-show" alt="image">
                </div>
                <div class="span6">
                    <h2><%= @movie.name %></h2>

                   <ul class="showpagetext project-info">
                        <li>In Theaters:&nbsp;&nbsp;&nbsp;<%= @movie.release_date_theater ? @movie.release_date_theater.to_formatted_s(:nice_date) : "Check back soon!" %>
                        </h6></li>
                        <li>On DVD:&nbsp;&nbsp;&nbsp;<%= @movie.release_date_dvd ? @movie.release_date_dvd.to_formatted_s(:nice_date) : "Check back soon!" %>
                        </li>
                        <li>More Info:&nbsp;&nbsp; <%= link_to "Rotten Tomatoes", @movie.rotten_tomatoes_link, target: "blank", style: "color: #666; text-decoration:underline;"%>
                        </li>

                        <li>
                            <% if current_user %>
                                <%= link_to "Add This Movie", user_movies_path(current_user, :movie_id => @movie), :method => :post %>
                            <% else %>
                                <%= link_to "Sign Up to Track Movies", new_user_registration_path %>
                            <% end %>
                        </li>
                    </ul>
                </div>
            </div>

        </div><!-- End gallery-single-->

    </div><!-- End container row -->

    </div> <!-- End Container -->

app/views/search/index.html.erb
 <div class="row">
        <!-- Gallery Items
        ================================================== -->
        <div class="span12 gallery">

            <div class="row clearfix">
                <ul class="gallery-post-grid holder">

                    <!-- Gallery Item 1 -->
            <% if @results.empty? %>
                <div class="span6"><h5>Sorry, there were no movies matching your search.</h5></div>
            <% else %>
                <% @results.each do |movie| %>
                    <li  class="span4 gallery-item" data-id="id-1" data-type="tag1">
                    <span class="link-like" onclick="window.location='<%= movie_path(movie) %>'">
                        <span class="gallery-hover-3col hidden-phone hidden-tablet">
                            <span class="gallery-icons">
                                <%= link_to "", user_movies_path(current_user, :movie_id => movie), :method => :post, class: "item-details-link" %>
                            </span>
                        </span>
                    </span>
                        <a href="<%= movie_path(movie) %>"><img src="<%= movie.poster_image %>" class="thumbnail-movie" alt="Gallery"></a>
                        <span class="project-details"><a href="<%= movie_path(movie) %>"><%= movie.name %></a><br>Theaters: <%= movie.release_date_theater ? movie.release_date_theater.to_formatted_s(:nice_date) : "Check back soon!" %><br>DVD: <%= movie.release_date_dvd ? movie.release_date_dvd.to_formatted_s(:nice_date) : "Check back soon!" %></span>
                    </li>
                <% end %>
            <% end %>

                </ul>
            </div>


        </div><!-- End gallery list-->

    </div><!-- End container row -->

    </div> <!-- End Container -->

app/views/search/new.html.erb
<%#= form_tag("/results", method: "get") do %>
 <%#= label_tag(:q, "Search for:") %>
 <%#= text_field_tag(:q) %>
 <%#= submit_tag("Search") %>
<%# end %>

app/views/shared/_footer.html.erb
    <!-- Footer Area
        ================================================== -->

    <div class="footer-container"><!-- Begin Footer -->
        <div class="container">
            <div class="row footer-row">
                <div class="span3 footer-col">

            <h4>TRACK YOUR TRAILER</h4>
            <div class="row"><!-- Begin Sub Footer -->
                <div class="span12 footer-col footer-sub">
                    <div class="row no-margin">
                        <div class="span6"><span class="left">© 2013 The Flatiron School. <a href="https://twitter.com/gregeng" target="blank">Greg Eng</a>, <a href="https://twitter.com/davidhenrybella" target="blank">David Bella</a>, <a href="https://twitter.com/emilyxxie" target="blank">Emily Xie</a></span></div>
                        <div class="span6">
                            <span class="right">
                            <%= link_to "Home", root_path %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                            <%= link_to "All Movies", all_movies_path %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                        <% if !current_user.nil? %>
                            <%= link_to "My Movies", current_user %>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                            <a href="<%= edit_user_registration_path %>">My Info</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                            <%= link_to "Logout", logout_path %>
                        <% else  %>
                            <%= link_to "Login", login_path %>
                        <% end %>
                            </span>

                        </div>
                    </div>
                </div>
            </div><!-- End Sub Footer -->

        </div>
    </div><!-- End Footer -->

app/views/shared/_header.html.erb
    <!-- Color Bars (above header)-->
    <div class="color-bar-1"></div>
    <div class="color-bar-2 color-bg"></div>

    <div class="container">

        <div class="row header"><!-- Begin Header -->


            <!-- Logo
            ================================================== -->
            <div class="span6 logo">
                <h1><a href="<%= root_path %>">TRACK YOUR TRAILER</a></h1><h4 class="tagline">&nbsp;Keep tabs on your favorite upcoming movies.</h4>
                <!-- <a href="index.htm"><%#= image_tag "wonder-logo.png" %><alt=""></a> -->
            </div>

app/views/shared/_main_nav.html.erb
<!-- Main Navigation
================================================== -->
    <div class="span6 navigation">

        <div class="navbar">

            <ul class="nav hidden-phone">
                <li><%= link_to "All Movies", all_movies_path, class: "navlink" %></li>
                <% if current_user %>
                  <li><%= link_to "My Movies", current_user %></li>
                  <li><a href="<%= edit_user_registration_path %>">My Info</a></li>
                  <li><%= link_to "Logout", logout_path, :id => 'top-nav-logout'%></li>
                  <% else %>
                    <li><%= link_to "Login", login_path, :id => 'top-nav-login' %></li>
                <% end %>
            </ul>

        </div><!-- .navbar .hidden-phone -->

app/views/shared/_mobile_nav.html.erb
<!-- Mobile Nav
    ================================================== -->
    <form action="#" id="mobile-nav" class="visible-phone">
        <div class="mobile-nav-select">
        <select onchange="window.open(this.options[this.selectedIndex].value,'_top')">
            <option value="">Navigate...</option>
            <option value="<%= root_path %>">Home</option>
                <option value="<%= all_movies_path %>">- All Movies</option>
                <% if current_user %>
                    <option value="<%= user_path(current_user) %>">- My Movies</option>
                    <option value="<%= edit_user_registration_path %>">- My Info</option>
                    <option value="<%= current_user %>">Logout</option>
                <% else %>
                    <option value="<%= login_path %>">Login</option>
                <% end %>
        </select>
        </div>
    </form>

app/views/shared/_search.html.erb
  <%= form_tag("/results", method: "get", class: "form-search") do %>
      <div class="input-append">
          <%= text_field_tag(:q, nil, class: "span3 search-query") %>
          <%= submit_tag("Search", class: "btn") %>
      </div>
   <% end %>
</div>

app/views/users/index.html.erb
<%#= @users.collect(&:name).to_sentence %>
<% @users.each do |user| %>
<%= link_to user.name, user %><br>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %><br>
  <%= f.label :email %>
  <%= f.text_field :email %><br>
  <%= f.label :phone_number %>
  <%= f.phone_field :phone_number %><br>
  <%= f.label :password %>
  <%= f.password_field :password %><br>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<div class="span12"><h2>My Movies:</h2><br><br></div>




<!-- Page Content
    ================================================== -->
    <div class="row">

        <!-- Gallery Items
        ================================================== -->
  <% @user.movies.each do |movie| %>
        <div class="span12 gallery-single">
            <div class="row">
                <div class="span0">
                </div>
                <div class="span4">
                    <a href="<%= movie_path(movie)%>"><img src=<%= movie.poster_image %> class="profile-movie" alt="image"></a>
                </div>
                <div class="span1">
                </div>
                <div class="span7" style="margin: 0px; 0px; 0px; 5px;">
                    <h3><%= movie.name %></h3>
<!--                     <p class="lead">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla iaculis mattis lorem, quis gravida nunc iaculis ac.</p>
 -->
                    <ul class="showpagetext project-info">
                        <li>In Theaters:&nbsp;&nbsp;&nbsp;<%= movie.release_date_theater ? movie.release_date_theater.to_formatted_s(:nice_date) : "Check back soon!" %></h6></li>
                        <li>On DVD:&nbsp;&nbsp;&nbsp;<%= movie.release_date_dvd ? movie.release_date_dvd.to_formatted_s(:nice_date) : "Check back soon!" %></li>
                        <li>More Info:&nbsp;&nbsp; <%= link_to "Rotten Tomatoes", movie.rotten_tomatoes_link, target: "blank", style: "color: #666; text-decoration:underline;"%>
                        </li>
                        <li>
                            <%= link_to "Remove From My List", user_movie_path(@user, movie), :method => :delete, data: { confirm: 'Are you sure?' } %>
                        </li>
                    </ul>
                </div>
            </div>
             <ul class="showpagetext project-info"><li></li><ul>
        </div><!-- End gallery-single-->

        <% end %>

    </div><!-- End container row -->

    </div> <!-- End Container -->